### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by madeInLagny** [mauriciotogneri/firebase-localization#2]
Hi, thanks for this great plugin. I would like to use it as a generator of i18Next translation file.
i18Next uses file namespaces to reduce file size. Is there a way to introduce multiple files per language based on namespaces ?

**Comment by mauriciotogneri** [comment]
Hi, I'm glad you like the tool.
I'm not sure I understood your question. You mean that when downloading the translations for a language in i18Next format you will have to download multiple files instead of just one?
The tool works currently with single files for both download and upload translations. If you need to work with several files you will have to change the source code to support that.

**Comment by madeInLagny** [comment]
Hi,
Yes, this is what I meant. I will have a look at the source code and see if
I can make a PR for it.


Le dim. 17 nov. 2019 à 21:30, Mauricio Togneri <notifications@github.com> a
écrit :
